# Generated by Django 6.1.1 on 2026-09-13 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts_id', models.CharField(max_length=20, unique=True, verbose_name='identifiant CTS')),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom en français')),
                ('name_en', models.CharField(max_length=100, verbose_name='nom en anglais')),
                ('latin_name', models.CharField(max_length=100, verbose_name='nom latin')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='abréviation')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='année de naissance')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='année de mort')),
                ('period', models.CharField(blank=True, choices=[('archaic', 'latin archaïque'), ('classical', 'latin classique'), ('imperial', 'latin impérial'), ('late', 'latin tardif'), ('medieval', 'latin médiéval'), ('neo', 'néo-latin')], max_length=20, verbose_name='époque')),
            ],
            options={
                'verbose_name': 'auteur',
                'verbose_name_plural': 'auteurs',
                'ordering': ['birth_year', 'cts_id'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts_urn', models.CharField(max_length=120, verbose_name='URN CTS')),
                ('source', models.CharField(max_length=100, verbose_name='source')),
                ('source_path', models.CharField(max_length=255, verbose_name='fichier')),
                ('source_version', models.CharField(help_text='Commit Git du dépôt importé.', max_length=40, verbose_name='version de la source')),
                ('license', models.CharField(max_length=50, verbose_name='licence')),
                ('citation_scheme', models.JSONField(blank=True, default=list, verbose_name='schéma de citation')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='importée le')),
                ('is_current', models.BooleanField(default=True, verbose_name='édition en usage')),
                ('passage_count', models.PositiveIntegerField(default=0, verbose_name='nombre de passages')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='nombre de mots')),
            ],
            options={
                'verbose_name': 'édition',
                'verbose_name_plural': 'éditions',
                'ordering': ['work', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ordre')),
                ('reference', models.CharField(max_length=50, verbose_name='référence')),
                ('heading', models.CharField(blank=True, max_length=300, verbose_name='titre')),
                ('text', models.TextField(verbose_name='texte')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='corpus.edition', verbose_name='édition')),
            ],
            options={
                'verbose_name': 'passage',
                'verbose_name_plural': 'passages',
                'ordering': ['edition', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='position dans l’édition')),
                ('form', models.CharField(max_length=200, verbose_name='forme imprimée')),
                ('norm', models.CharField(max_length=200, verbose_name='forme normalisée')),
                ('before', models.CharField(blank=True, max_length=50, verbose_name='ponctuation avant')),
                ('after', models.CharField(blank=True, max_length=200, verbose_name='ponctuation et espace après')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='mot étranger')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.edition', verbose_name='édition')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.passage', verbose_name='passage')),
            ],
            options={
                'verbose_name': 'mot',
                'verbose_name_plural': 'mots',
                'ordering': ['edition', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts_urn', models.CharField(max_length=100, unique=True, verbose_name='URN CTS')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('abbreviation', models.CharField(blank=True, max_length=30, verbose_name='abréviation')),
                ('genre', models.CharField(blank=True, choices=[('oratory', 'éloquence'), ('rhetoric', 'rhétorique'), ('philosophy', 'philosophie'), ('letters', 'lettres'), ('history', 'histoire'), ('tragedy', 'tragédie'), ('satire', 'satire ménippée')], max_length=20, verbose_name='genre')),
                ('register', models.CharField(blank=True, choices=[('elevated', 'soutenu'), ('standard', 'courant'), ('familiar', 'familier')], max_length=20, verbose_name='registre')),
                ('form', models.CharField(choices=[('prose', 'prose'), ('verse', 'vers'), ('prosimetrum', 'prosimètre')], default='prose', max_length=20, verbose_name='forme')),
                ('date_from', models.IntegerField(blank=True, null=True, verbose_name='date de début')),
                ('date_to', models.IntegerField(blank=True, null=True, verbose_name='date de fin')),
                ('is_core', models.BooleanField(default=False, help_text='Les attestations du noyau sont vérifiées par des personnes.', verbose_name='noyau')),
                ('is_fragmentary', models.BooleanField(default=False, verbose_name='fragmentaire')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='corpus.author', verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'œuvre',
                'verbose_name_plural': 'œuvres',
                'ordering': ['author__birth_year', 'cts_urn'],
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='corpus.work', verbose_name='œuvre'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('edition', 'order'), name='corpus_passage_order'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('edition', 'reference'), name='corpus_passage_reference'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['norm'], name='corpus_token_norm', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('edition', 'position'), name='corpus_token_position'),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('cts_urn', 'source_version'), name='corpus_edition_version'),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('work',), name='corpus_one_current_edition'),
        ),
    ]
