# Generated by Django 6.1.1 on 2026-09-13 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100, verbose_name='outil')),
                ('tool_version', models.CharField(blank=True, max_length=50, verbose_name='version de l’outil')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créée le')),
                ('is_default', models.BooleanField(default=False, help_text='Couche utilisée par la recherche par lemme.', verbose_name='couche par défaut')),
                ('editions', models.ManyToManyField(blank=True, related_name='analysis_layers', to='corpus.edition', verbose_name='éditions analysées')),
            ],
            options={
                'verbose_name': 'couche d’analyse',
                'verbose_name_plural': 'couches d’analyse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(default=0, verbose_name='partie du mot')),
                ('text', models.CharField(max_length=200, verbose_name='texte analysé')),
                ('lemma', models.CharField(blank=True, max_length=200, verbose_name='lemme')),
                ('lemma_norm', models.CharField(blank=True, max_length=200, verbose_name='lemme normalisé')),
                ('upos', models.CharField(blank=True, max_length=10, verbose_name='catégorie')),
                ('feats', models.CharField(blank=True, max_length=300, verbose_name='traits morphologiques')),
                ('head_part', models.PositiveSmallIntegerField(default=0, verbose_name='partie de la tête')),
                ('deprel', models.CharField(blank=True, max_length=30, verbose_name='relation syntaxique')),
                ('sentence', models.PositiveIntegerField(default=0, verbose_name='phrase')),
                ('origin', models.CharField(choices=[('verified', 'import vérifié'), ('automatic', 'automatique'), ('corrected', 'correction humaine')], default='automatic', max_length=10, verbose_name='origine')),
                ('head', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.token', verbose_name='tête syntaxique')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='corpus.analysislayer', verbose_name='couche')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='corpus.token', verbose_name='mot')),
            ],
            options={
                'verbose_name': 'analyse d’un mot',
                'verbose_name_plural': 'analyses des mots',
                'ordering': ['layer', 'token', 'part'],
            },
        ),
        migrations.AddConstraint(
            model_name='analysislayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='corpus_one_default_layer'),
        ),
        migrations.AddIndex(
            model_name='tokenanalysis',
            index=models.Index(fields=['layer', 'lemma_norm'], name='corpus_analysis_lemma', opclasses=['int8_ops', 'varchar_pattern_ops']),
        ),
        migrations.AddConstraint(
            model_name='tokenanalysis',
            constraint=models.UniqueConstraint(fields=('layer', 'token', 'part'), name='corpus_analysis_part'),
        ),
    ]
