# Generated by Django 6.1.1 on 2026-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, choices=[('oratory', 'éloquence'), ('rhetoric', 'rhétorique'), ('philosophy', 'philosophie'), ('letters', 'lettres'), ('history', 'histoire'), ('biography', 'biographie'), ('technical', 'traité technique'), ('miscellany', 'miscellanées'), ('novel', 'roman'), ('tragedy', 'tragédie'), ('comedy', 'comédie'), ('epic', 'épopée'), ('didactic', 'poésie didactique'), ('bucolic', 'bucolique'), ('lyric', 'poésie lyrique'), ('elegy', 'élégie'), ('epigram', 'épigramme'), ('fable', 'fable'), ('satire', 'satire')], max_length=20, verbose_name='genre'),
        ),
    ]
