# Generated by Django 6.1.1 on 2026-09-14 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_work_genres_enlarged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5, verbose_name='langue')),
                ('translator', models.CharField(max_length=200, verbose_name='traducteur')),
                ('translator_death_year', models.IntegerField(blank=True, null=True, verbose_name='mort du traducteur')),
                ('published', models.IntegerField(blank=True, null=True, verbose_name='parution')),
                ('source', models.CharField(max_length=100, verbose_name='source')),
                ('source_path', models.CharField(max_length=255, verbose_name='fichier')),
                ('source_version', models.CharField(max_length=40, verbose_name='version de la source')),
                ('license', models.CharField(max_length=100, verbose_name='licence')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='importée le')),
                ('is_current', models.BooleanField(default=True, verbose_name='traduction en usage')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='corpus.work', verbose_name='œuvre')),
            ],
            options={
                'verbose_name': 'traduction en regard',
                'verbose_name_plural': 'traductions en regard',
                'ordering': ['work', 'language', 'translator'],
            },
        ),
        migrations.CreateModel(
            name='TranslationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ordre')),
                ('reference', models.CharField(max_length=50, verbose_name='référence')),
                ('text', models.TextField(verbose_name='texte')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='corpus.referencetranslation', verbose_name='traduction')),
            ],
            options={
                'verbose_name': 'partie d’une traduction',
                'verbose_name_plural': 'parties des traductions',
                'ordering': ['translation', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='referencetranslation',
            constraint=models.UniqueConstraint(fields=('source_path', 'source_version'), name='corpus_translation_version'),
        ),
        migrations.AddConstraint(
            model_name='translationpart',
            constraint=models.UniqueConstraint(fields=('translation', 'order'), name='corpus_part_order'),
        ),
        migrations.AddConstraint(
            model_name='translationpart',
            constraint=models.UniqueConstraint(fields=('translation', 'reference'), name='corpus_part_reference'),
        ),
    ]
