# Generated by Django 6.1.1 on 2026-09-14 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_reference_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('part', models.PositiveSmallIntegerField(default=0, verbose_name='partie du mot')),
                ('lemma', models.CharField(blank=True, max_length=200, verbose_name='lemme')),
                ('upos', models.CharField(blank=True, max_length=10, verbose_name='catégorie')),
                ('feats', models.CharField(blank=True, max_length=300, verbose_name='traits morphologiques')),
                ('deprel', models.CharField(blank=True, max_length=30, verbose_name='relation syntaxique')),
                ('reason', models.TextField(max_length=1000, verbose_name='motif')),
                ('status', models.CharField(choices=[('proposed', 'proposée'), ('validated', 'validée'), ('rejected', 'rejetée')], default='proposed', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='proposée le')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='examinée le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_corrections', to=settings.AUTH_USER_MODEL, verbose_name='proposée par')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.token', verbose_name='tête syntaxique')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='examinée par')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='corpus.token', verbose_name='mot')),
            ],
            options={
                'verbose_name': 'correction d’analyse',
                'verbose_name_plural': 'corrections d’analyse',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='corpus_correction_status')],
            },
        ),
    ]
