# Generated by Django 6.1.1 on 2026-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_analysis_correction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tokenanalysis',
            index=models.Index(fields=['layer', 'head', 'head_part'], name='corpus_analysis_head'),
        ),
    ]
