# Generated by Django 6.1.1 on 2026-09-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_tokenanalysis_corpus_analysis_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, verbose_name='personnage'),
        ),
    ]
