# Generated by Django 6.1.1 on 2026-09-14 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='version')),
                ('text', models.TextField(help_text='Une ligne « ## Titre » ou « ### Titre » fait un intertitre ; les lignes qui commencent par « - » font une liste ; une ligne vide sépare les paragraphes.', max_length=100000, verbose_name='texte')),
                ('summary', models.CharField(blank=True, help_text='Facultatif : ce que cette version change par rapport à la précédente.', max_length=300, verbose_name='ce qui change')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='publiée le')),
                ('published_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publiée par')),
            ],
            options={
                'verbose_name': 'version du guide d’annotation',
                'verbose_name_plural': 'versions du guide d’annotation',
                'ordering': ['-number'],
            },
        ),
    ]
