# Generated by Django 6.1.1 on 2026-09-14 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
        ('justifications', '0003_alter_evidence_justification_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('definition', models.TextField(max_length=1000, verbose_name='sens')),
                ('register', models.CharField(blank=True, choices=[('elevated', 'soutenu'), ('standard', 'courant'), ('familiar', 'familier')], max_length=20, verbose_name='registre')),
                ('usage_note', models.CharField(blank=True, max_length=300, verbose_name='note d’usage')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retiré')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
            ],
            options={
                'verbose_name': 'sens',
                'verbose_name_plural': 'sens',
                'ordering': ['unit', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Equivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('language', models.CharField(choices=[('fr', 'français'), ('en', 'anglais'), ('de', 'allemand'), ('it', 'italien'), ('es', 'espagnol')], max_length=2, verbose_name='langue')),
                ('expression', models.CharField(max_length=200, verbose_name='expression')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retiré')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalents', to='phraseology.sense', verbose_name='sens')),
            ],
            options={
                'verbose_name': 'équivalent',
                'verbose_name_plural': 'équivalents',
                'ordering': ['sense', 'language', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('reference_form', models.CharField(help_text='La forme sous laquelle on cite l’unité, par exemple : consilium capere.', max_length=200, verbose_name='forme de référence')),
                ('kind', models.CharField(blank=True, choices=[('verb-noun', 'collocation verbe–nom'), ('adjective-noun', 'collocation adjectif–nom'), ('adverb-verb', 'collocation adverbe–verbe'), ('noun-noun', 'collocation nom–nom'), ('fixed', 'locution figée'), ('formula', 'formule'), ('open-slot', 'construction à case vide'), ('discourse', 'marqueur de discours'), ('clausula', 'clausule')], max_length=20, verbose_name='type')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='étiquettes')),
                ('schema', models.CharField(blank=True, help_text='Lemmes et relations syntaxiques, le mot qui régit d’abord : capio -obj-> consilium. Plusieurs relations se séparent par « ; », des variantes par « | ».', max_length=300, verbose_name='schéma')),
                ('construction', models.CharField(blank=True, help_text='Par exemple : consilium capere + infinitif, ou + ut et le subjonctif.', max_length=300, verbose_name='construction')),
                ('register', models.CharField(blank=True, choices=[('elevated', 'soutenu'), ('standard', 'courant'), ('familiar', 'familier')], max_length=20, verbose_name='registre')),
                ('usage_marks', models.JSONField(blank=True, default=list, verbose_name='marques d’usage')),
                ('status', models.CharField(choices=[('draft', 'brouillon'), ('proposed', 'proposée'), ('validated', 'validée'), ('contested', 'contestée')], default='draft', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créée le')),
                ('validated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='validée le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('validated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'unité phraséologique',
                'verbose_name_plural': 'unités phraséologiques',
                'ordering': ['reference_form', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sense',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senses', to='phraseology.unit', verbose_name='unité'),
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('form', models.CharField(max_length=200, verbose_name='forme type')),
                ('variation', models.CharField(choices=[('base', 'forme de base'), ('passive', 'passif'), ('word-order', 'ordre des mots'), ('insertion', 'insertion'), ('lexical', 'variante lexicale'), ('other', 'autre')], default='base', max_length=20, verbose_name='nature de la variation')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retirée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajoutée le')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizations', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'réalisation',
                'verbose_name_plural': 'réalisations',
                'ordering': ['unit', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('level', models.CharField(choices=[('validated', 'vérifiée par des personnes'), ('automatic', 'repérée automatiquement')], default='validated', editable=False, max_length=10, verbose_name='niveau')),
                ('origin', models.CharField(choices=[('manual', 'saisie manuelle'), ('candidate', 'candidat'), ('query', 'requête')], default='manual', editable=False, max_length=10, verbose_name='origine')),
                ('status', models.CharField(choices=[('proposed', 'proposée'), ('validated', 'validée'), ('rejected', 'rejetée')], default='proposed', editable=False, max_length=10, verbose_name='statut')),
                ('is_example', models.BooleanField(default=False, help_text='Montré en tête de la fiche.', verbose_name='exemple choisi')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retirée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajoutée le')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='examinée le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='examinée par')),
                ('tokens', models.ManyToManyField(related_name='+', to='corpus.token', verbose_name='mots couverts')),
                ('realization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='phraseology.realization', verbose_name='réalisation')),
                ('sense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='phraseology.sense', verbose_name='sens')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'attestation',
                'verbose_name_plural': 'attestations',
                'ordering': ['unit', '-is_example', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('locator', models.CharField(help_text='Paragraphe, page ou entrée : « § 426 », « s. v. consilium ».', max_length=100, verbose_name='localisation')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retiré')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='phraseology.unit', verbose_name='unité')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='justifications.bibliographicwork', verbose_name='ouvrage')),
            ],
            options={
                'verbose_name': 'renvoi bibliographique',
                'verbose_name_plural': 'renvois bibliographiques',
                'ordering': ['unit', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('kind', models.CharField(choices=[('synonym', 'synonyme de'), ('variant', 'variante de'), ('antonym', 'antonyme de'), ('broader', 'plus général que'), ('narrower', 'plus précis que')], max_length=10, verbose_name='relation')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retirée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajoutée le')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phraseology.unit', verbose_name='unité liée')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'relation entre unités',
                'verbose_name_plural': 'relations entre unités',
                'ordering': ['unit', 'kind', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'reference_form'], name='phraseology_unit_status'),
        ),
        migrations.AddConstraint(
            model_name='attestation',
            constraint=models.CheckConstraint(condition=models.Q(('level', 'automatic'), ('status', 'validated'), _negated=True), name='phraseology_automatic_never_validated'),
        ),
        migrations.AddConstraint(
            model_name='unitrelation',
            constraint=models.CheckConstraint(condition=models.Q(('unit', models.F('target')), _negated=True), name='phraseology_relation_two_units'),
        ),
        migrations.AddConstraint(
            model_name='unitrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_withdrawn', False)), fields=('unit', 'target', 'kind'), name='phraseology_one_active_relation'),
        ),
    ]
