# Generated by Django 6.1.1 on 2026-09-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(max_length=300, verbose_name='schéma')),
                ('total', models.PositiveIntegerField(verbose_name='occurrences')),
                ('core_total', models.PositiveIntegerField(verbose_name='occurrences dans le noyau')),
                ('by_author', models.JSONField(default=list, verbose_name='répartition par auteur')),
                ('corpus_version', models.CharField(max_length=200, verbose_name='version du corpus')),
                ('computed_at', models.DateTimeField(verbose_name='calculée le')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequency', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'fréquence',
                'verbose_name_plural': 'fréquences',
            },
        ),
    ]
