# Generated by Django 6.1.1 on 2026-09-14 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0002_unitfrequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neologism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('form', models.CharField(max_length=200, verbose_name='forme latine')),
                ('meaning', models.TextField(help_text='La réalité moderne que le mot désigne, par exemple : la bicyclette.', max_length=1000, verbose_name='sens moderne')),
                ('formation', models.CharField(choices=[('periphrasis', 'périphrase'), ('derivation', 'dérivation'), ('borrowing', 'emprunt')], max_length=20, verbose_name='formation')),
                ('justification', models.TextField(help_text='Pourquoi ce choix : modèles anciens, analogies, usage des latinistes modernes. Les preuves du corpus et des ouvrages s’ajoutent ci-dessous.', max_length=3000, verbose_name='justification')),
                ('lrl_reference', models.CharField(blank=True, help_text='Facultatif : l’entrée ou la page, citée sans extrait (« s. v. birota »).', max_length=100, verbose_name='Lexicon recentis Latinitatis')),
                ('status', models.CharField(choices=[('proposed', 'proposé'), ('validated', 'validé')], default='proposed', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='proposé le')),
                ('validated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='validé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neologisms', to=settings.AUTH_USER_MODEL, verbose_name='proposé par')),
                ('validated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'néologisme',
                'verbose_name_plural': 'néologismes',
                'ordering': ['form', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NeologismEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('language', models.CharField(choices=[('fr', 'français'), ('en', 'anglais'), ('de', 'allemand'), ('it', 'italien'), ('es', 'espagnol')], max_length=2, verbose_name='langue')),
                ('expression', models.CharField(max_length=200, verbose_name='expression')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retiré')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
                ('neologism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalents', to='phraseology.neologism', verbose_name='néologisme')),
            ],
            options={
                'verbose_name': 'équivalent d’un néologisme',
                'verbose_name_plural': 'équivalents des néologismes',
                'ordering': ['neologism', 'language', 'created_at', 'pk'],
            },
        ),
    ]
