# Generated by Django 6.1.1 on 2026-09-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
        ('phraseology', '0003_neologism_neologismequivalent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200, verbose_name='lemme qui régit')),
                ('relation', models.CharField(max_length=30, verbose_name='relation')),
                ('dependent', models.CharField(max_length=200, verbose_name='lemme dépendant')),
                ('frequency', models.PositiveIntegerField(verbose_name='fréquence')),
                ('score', models.FloatField(verbose_name='score d’association')),
                ('corpus_version', models.CharField(max_length=200, verbose_name='version du corpus')),
                ('extracted_at', models.DateTimeField(verbose_name='extrait le')),
                ('status', models.CharField(choices=[('pending', 'à examiner'), ('retained', 'retenu'), ('rejected', 'rejeté')], default='pending', max_length=10, verbose_name='statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décidé le')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='décidé par')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.analysislayer', verbose_name='couche d’analyse')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'candidat',
                'verbose_name_plural': 'candidats',
                'ordering': ['-score', 'pk'],
                'indexes': [models.Index(fields=['status', '-score'], name='phraseology_candidate_queue')],
                'constraints': [models.UniqueConstraint(fields=('head', 'relation', 'dependent'), name='phraseology_one_candidate_per_pair')],
            },
        ),
    ]
