# Generated by Django 6.1.1 on 2026-09-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0004_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=201, verbose_name='lemme')),
                ('norm', models.CharField(max_length=200, verbose_name='forme normalisée')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'forme d’une unité',
                'verbose_name_plural': 'formes des unités',
                'indexes': [models.Index(fields=['norm'], name='phraseology_unit_form_norm')],
                'constraints': [models.UniqueConstraint(fields=('unit', 'lemma', 'norm'), name='phraseology_unit_form')],
            },
        ),
    ]
