# Generated by Django 6.1.1 on 2026-09-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0005_unitform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(max_length=300, verbose_name='schéma')),
                ('corpus_version', models.CharField(max_length=200, verbose_name='version du corpus')),
                ('found', models.PositiveIntegerField(verbose_name='occurrences repérées')),
                ('added', models.PositiveIntegerField(verbose_name='attestations ajoutées')),
                ('remaining', models.PositiveIntegerField(verbose_name='occurrences restant à relever')),
                ('surveyed_at', models.DateTimeField(verbose_name='relevé le')),
                ('surveyed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='relevé par')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='phraseology.unit', verbose_name='unité')),
            ],
            options={
                'verbose_name': 'relevé',
                'verbose_name_plural': 'relevés',
            },
        ),
    ]
