# Generated by Django 6.1.1 on 2026-09-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0006_unitsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsurvey',
            name='core_found',
            field=models.PositiveIntegerField(default=0, verbose_name='dont dans le noyau'),
        ),
    ]
