# Generated by Django 6.1.1 on 2026-09-14 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0007_unitsurvey_core_found'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('expression', models.CharField(help_text='Ce que la recherche devait trouver, par exemple : consilium sumere.', max_length=200, verbose_name='expression cherchée')),
                ('query', models.CharField(editable=False, max_length=2000, verbose_name='requête')),
                ('corpus_version', models.CharField(editable=False, max_length=200, verbose_name='version du corpus')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='enregistrée le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negative_searches', to=settings.AUTH_USER_MODEL, verbose_name='enregistrée par')),
            ],
            options={
                'verbose_name': 'recherche infructueuse',
                'verbose_name_plural': 'recherches infructueuses',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
