# Generated by Django 6.1.1 on 2026-09-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_work_genres_enlarged'),
        ('phraseology', '0008_negativesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('core', 'noyau'), ('prose', 'toute la prose'), ('all', 'tout le corpus')], max_length=10, verbose_name='partie du corpus')),
                ('head', models.CharField(max_length=200, verbose_name='lemme qui régit')),
                ('relation', models.CharField(max_length=30, verbose_name='relation')),
                ('dependent', models.CharField(max_length=200, verbose_name='lemme dépendant')),
                ('frequency', models.PositiveIntegerField(verbose_name='fréquence')),
                ('score', models.FloatField(verbose_name='score d’association')),
                ('corpus_version', models.CharField(max_length=200, verbose_name='version du corpus')),
                ('computed_at', models.DateTimeField(verbose_name='calculée le')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.analysislayer', verbose_name='couche d’analyse')),
            ],
            options={
                'verbose_name': 'collocation',
                'verbose_name_plural': 'collocations',
                'indexes': [models.Index(fields=['scope', 'head', 'relation', '-score'], name='phraseology_colloc_head'), models.Index(fields=['scope', 'dependent', 'relation', '-score'], name='phraseology_colloc_dep')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'head', 'relation', 'dependent'), name='phraseology_one_collocation_per_pair')],
            },
        ),
    ]
