# Generated by Django 6.1.1 on 2026-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0009_collocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='example_proposed',
            field=models.BooleanField(default=False, help_text='Proposée en annotant le texte ; un relecteur décide d’en faire un exemple.', verbose_name='proposée comme exemple'),
        ),
    ]
