# Generated by Django 6.1.1 on 2026-09-14 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0010_attestation_example_proposed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='is_contested',
            field=models.BooleanField(default=False, editable=False, verbose_name='contestée'),
        ),
        migrations.CreateModel(
            name='AttestationDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('reason', models.TextField(max_length=1000, verbose_name='motif')),
                ('status', models.CharField(choices=[('open', 'ouvert'), ('kept', 'attestation maintenue'), ('rejected', 'attestation rejetée')], default='open', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='signalé le')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='tranché le')),
                ('attestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doubts', to='phraseology.attestation', verbose_name='attestation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestation_doubts', to=settings.AUTH_USER_MODEL, verbose_name='signalé par')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tranché par')),
            ],
            options={
                'verbose_name': 'doute sur une attestation',
                'verbose_name_plural': 'doutes sur des attestations',
                'ordering': ['attestation', 'created_at', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('attestation', 'created_by'), name='phraseology_one_open_doubt_per_author')],
            },
        ),
    ]
