# Generated by Django 6.1.1 on 2026-09-14 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_analysis_correction'),
        ('phraseology', '0011_attestation_doubts_and_contests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('status', models.CharField(choices=[('open', 'à rattacher'), ('attached', 'rattaché à une fiche'), ('dismissed', 'classé sans suite')], default='open', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='repéré le')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='traité le')),
                ('attestation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='phraseology.attestation', verbose_name='attestation obtenue')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to=settings.AUTH_USER_MODEL, verbose_name='repéré par')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('tokens', models.ManyToManyField(related_name='+', to='corpus.token', verbose_name='mots')),
            ],
            options={
                'verbose_name': 'repérage',
                'verbose_name_plural': 'repérages',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='phraseology_sighting_queue')],
            },
        ),
    ]
