# Generated by Django 6.1.1 on 2026-09-14 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_analysis_correction'),
        ('phraseology', '0012_sighting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='relu le')),
                ('corpus_version', models.CharField(max_length=200, verbose_name='version du corpus')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retirée')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='retirée le')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passage_reviews', to=settings.AUTH_USER_MODEL, verbose_name='relu par')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='retirée par')),
            ],
            options={
                'verbose_name': 'passage entièrement relu',
                'verbose_name_plural': 'passages entièrement relus',
                'ordering': ['-reviewed_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_withdrawn', False)), fields=('passage',), name='phraseology_one_standing_review')],
            },
        ),
    ]
