# Generated by Django 6.1.1 on 2026-09-14 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_analysis_correction'),
        ('phraseology', '0013_passage_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('text', models.TextField(max_length=2000, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='écrite le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_notes', to=settings.AUTH_USER_MODEL, verbose_name='écrite par')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('tokens', models.ManyToManyField(related_name='+', to='corpus.token', verbose_name='mots')),
            ],
            options={
                'verbose_name': 'note de lecture',
                'verbose_name_plural': 'notes de lecture',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
