# Generated by Django 6.1.1 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0014_reading_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='marked_form',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='forme de référence balisée'),
        ),
    ]
