# Generated by Django 6.1.1 on 2026-09-19 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0016_schema_optional_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('name', models.CharField(help_text='Le nom écrit entre accolades dans les schémas et les formes de référence : liquide pour {liquide}. Lettres minuscules sans accents et traits d’union ; il ne change plus ensuite.', max_length=40, unique=True, verbose_name='nom')),
                ('label', models.CharField(help_text='Ce que le mot désigne, par exemple : nom désignant un liquide.', max_length=100, verbose_name='intitulé')),
                ('definition', models.TextField(blank=True, help_text='Facultatif : ce qui entre dans la classe et ce qui n’y entre pas.', max_length=1000, verbose_name='définition')),
                ('rules', models.JSONField(default=list, verbose_name='règles')),
                ('status', models.CharField(choices=[('proposed', 'proposé'), ('validated', 'validé')], default='proposed', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='proposé le')),
                ('validated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='validé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abstract_words', to=settings.AUTH_USER_MODEL, verbose_name='proposé par')),
                ('validated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'mot abstrait',
                'verbose_name_plural': 'mots abstraits',
                'ordering': ['name'],
            },
        ),
    ]
