# Generated by Django 6.1.1 on 2026-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0017_abstract_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='schema',
            field=models.CharField(blank=True, help_text='Lemmes et relations syntaxiques, le mot qui régit d’abord : capio -obj-> consilium. Plusieurs relations se séparent par « ; », des variantes par « | ». Une relation facultative s’écrit entre parenthèses : gero -(sp)-> cum ; un mot abstrait, entre accolades : sumo -obj-> {liquide}.', max_length=300, verbose_name='schéma'),
        ),
    ]
