# Generated by Django 6.1.1 on 2026-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0018_schema_abstract_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='kind',
            field=models.CharField(blank=True, choices=[('verb-noun', 'collocation verbe–nom'), ('adjective-noun', 'collocation adjectif–nom'), ('adverb-verb', 'collocation adverbe–verbe'), ('noun-noun', 'collocation nom–nom'), ('fixed', 'locution figée'), ('formula', 'formule'), ('open-slot', 'construction à case vide'), ('discourse', 'marqueur de discours'), ('clausula', 'clausule')], help_text='Le type ne dépend pas des mots abstraits : {liquide} sūmere reste une collocation verbe–nom. « Construction à case vide » désigne une construction dont une place reste ouverte à presque tout mot.', max_length=20, verbose_name='type'),
        ),
    ]
