# Generated by Django 6.1.1 on 2026-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0019_unit_kind_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitfrequency',
            name='abstract_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='mots abstraits'),
        ),
        migrations.AddField(
            model_name='unitsurvey',
            name='abstract_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='mots abstraits'),
        ),
    ]
