# Generated by Django 6.1.1 on 2026-09-13 16:50

import accounts.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='adult_declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de la déclaration de majorité'),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonymisé le'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', help_text='Nom visible sur vos contributions et votre page publique.', max_length=80, verbose_name='nom affiché'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='interface_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=8, verbose_name='langue d’interface'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='majorité déclarée'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Vrai après une première contribution validée : les limites des nouveaux comptes ne s’appliquent plus.', verbose_name='compte confirmé'),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, help_text='Facultatif, par exemple 0000-0002-1825-0097.', max_length=19, validators=[accounts.models.validate_orcid], verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
    ]
