# Generated by Django 6.1.1 on 2026-09-13 17:03

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='identifiant du contenu')),
                ('reason', models.CharField(choices=[('illegal', 'contenu manifestement illicite'), ('abuse', 'propos injurieux ou harcèlement'), ('copyright', 'atteinte au droit d’auteur'), ('spam', 'publicité ou spam'), ('error', 'erreur manifeste'), ('other', 'autre motif')], max_length=20, verbose_name='motif')),
                ('message', models.TextField(blank=True, max_length=2000, verbose_name='précisions')),
                ('status', models.CharField(choices=[('open', 'ouvert'), ('handled', 'traité'), ('rejected', 'rejeté')], default='open', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('resolution', models.TextField(blank=True, max_length=2000, verbose_name='suite donnée')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='moderation_report_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('author', 'content_type', 'object_id'), name='moderation_one_open_report_per_author')],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='identifiant du contenu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('action', models.CharField(choices=[('create', 'création'), ('update', 'modification'), ('revert', 'retour à une version précédente'), ('hide', 'masquage'), ('unhide', 'rétablissement')], max_length=10, verbose_name='action')),
                ('before', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='état avant')),
                ('after', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='état après')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='commentaire')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('reverted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='moderation.revision', verbose_name='version rétablie')),
            ],
            options={
                'verbose_name': 'révision',
                'verbose_name_plural': 'révisions',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='moderation_revision_object'), models.Index(fields=['author', 'created_at'], name='moderation_revision_author')],
            },
        ),
    ]
