# Generated by Django 6.1.1 on 2026-09-13 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='identifiant du contenu')),
                ('text', models.TextField(max_length=5000, verbose_name='message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='type de contenu')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='moderation_comment_object')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='identifiant du contenu')),
                ('value', models.SmallIntegerField(choices=[(1, 'pour'), (-1, 'contre')], verbose_name='avis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='type de contenu')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'constraints': [models.UniqueConstraint(fields=('author', 'content_type', 'object_id'), name='moderation_one_vote_per_author'), models.CheckConstraint(condition=models.Q(('value__in', [1, -1])), name='moderation_vote_value')],
            },
        ),
    ]
