# Generated by Django 6.1.1 on 2026-09-19 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('translations', '0010_version_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('version_published', 'a publié une version'), ('step_created', 'a créé une étape'), ('proposal_opened', 'a proposé des modifications'), ('proposal_closed', 'a examiné une proposition'), ('proposal_withdrawn', 'a retiré une proposition'), ('comment_posted', 'a écrit un message'), ('mentioned', 'vous a mentionné'), ('challenge_opened', 'a contesté un choix'), ('source_proposal_sent', 'a proposé de modifier un texte source'), ('source_proposal_closed', 'a examiné une proposition sur un texte'), ('member_invited', 'vous invite comme co-auteur'), ('member_joined', 'est devenu co-auteur'), ('member_declined', 'a refusé l’invitation'), ('topic_opened', 'a ouvert un sujet'), ('topic_closed', 'a fermé un sujet'), ('topic_reopened', 'a rouvert un sujet'), ('sentence_commented', 'a commenté une phrase')], max_length=30, verbose_name='action')),
                ('object_id', models.PositiveBigIntegerField()),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='translations.translationproject', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activity.event', verbose_name='événement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-event__created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'étoile',
                'verbose_name_plural': 'étoiles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True, verbose_name='suivi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', '-created_at'], name='activity_event_project'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['actor', '-created_at'], name='activity_event_actor'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='activity_notification_unread'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event'), name='activity_one_notification_per_event'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='activity_one_star'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['content_type', 'object_id'], name='activity_subscription_target'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='activity_one_subscription'),
        ),
    ]
