# Generated by Django 6.1.1 on 2026-09-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='verb',
            field=models.CharField(choices=[('version_published', 'a publié une version'), ('step_created', 'a créé une étape'), ('proposal_opened', 'a proposé des modifications'), ('proposal_closed', 'a examiné une proposition'), ('proposal_withdrawn', 'a retiré une proposition'), ('proposal_reviewed', 'a relu une proposition'), ('comment_posted', 'a écrit un message'), ('mentioned', 'vous a mentionné'), ('challenge_opened', 'a contesté un choix'), ('source_proposal_sent', 'a proposé de modifier un texte source'), ('source_proposal_closed', 'a examiné une proposition sur un texte'), ('member_invited', 'vous invite comme co-auteur'), ('member_joined', 'est devenu co-auteur'), ('member_declined', 'a refusé l’invitation'), ('topic_opened', 'a ouvert un sujet'), ('topic_closed', 'a fermé un sujet'), ('topic_reopened', 'a rouvert un sujet'), ('sentence_commented', 'a commenté une phrase')], max_length=30, verbose_name='action'),
        ),
    ]
