# Generated by Django 6.1.1 on 2026-09-13 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('author', models.CharField(blank=True, help_text='Pour un article de Wikipédia : « contributeurs de Wikipédia ».', max_length=200, verbose_name='auteur du texte')),
                ('author_death_year', models.IntegerField(blank=True, help_text='Obligatoire pour un texte du domaine public ; pour une œuvre anonyme, année de publication.', null=True, verbose_name='année de mort de l’auteur')),
                ('language', models.CharField(choices=[('fr', 'français'), ('en', 'anglais'), ('de', 'allemand'), ('it', 'italien'), ('es', 'espagnol')], max_length=2, verbose_name='langue')),
                ('source_url', models.URLField(blank=True, help_text='Obligatoire pour un texte sous licence libre, qui demande de citer sa source.', max_length=500, verbose_name='adresse d’origine')),
                ('license', models.CharField(choices=[('public-domain', 'domaine public'), ('cc0-1.0', 'CC0 1.0'), ('cc-by-4.0', 'CC BY 4.0'), ('cc-by-3.0', 'CC BY 3.0'), ('cc-by-sa-4.0', 'CC BY-SA 4.0'), ('cc-by-sa-3.0', 'CC BY-SA 3.0')], max_length=20, verbose_name='licence')),
                ('text', models.TextField(help_text='Une phrase par ligne ; une ligne vide entre deux paragraphes.', verbose_name='texte découpé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_texts', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
            ],
            options={
                'verbose_name': 'texte source',
                'verbose_name_plural': 'textes sources',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='numéro')),
                ('text', models.TextField(verbose_name='phrase')),
                ('starts_paragraph', models.BooleanField(default=False, verbose_name='début de paragraphe')),
                ('source_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='translations.sourcetext', verbose_name='texte source')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ['source_text', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcetext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('license', 'public-domain'), _negated=True), ('author_death_year__isnull', False), _connector='OR'), name='translations_public_domain_has_death_year'),
        ),
        migrations.AddConstraint(
            model_name='sourcetext',
            constraint=models.CheckConstraint(condition=models.Q(('license', 'public-domain'), models.Q(('source_url', ''), _negated=True), _connector='OR'), name='translations_free_license_has_source_url'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('source_text', 'order'), name='translations_segment_order'),
        ),
    ]
