# Generated by Django 6.1.1 on 2026-09-13 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_projects', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('source_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='translations.sourcetext', verbose_name='texte source')),
            ],
            options={
                'verbose_name': 'projet de traduction',
                'verbose_name_plural': 'projets de traduction',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TranslationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('style', models.CharField(choices=[('classical', 'classique, sans modèle particulier'), ('ciceronian', 'cicéronien'), ('caesarian', 'césarien'), ('sallustian', 'sallustien'), ('livian', 'livien'), ('senecan', 'sénéquien'), ('tacitean', 'tacitéen'), ('plinian', 'plinien (Pline le Jeune)'), ('late', 'latin tardif et chrétien'), ('humanist', 'humaniste'), ('contemporary', 'latin vivant contemporain')], max_length=20, verbose_name='style déclaré')),
                ('style_note', models.CharField(blank=True, help_text='Facultatif, par exemple : « Cicéron des lettres à Atticus ».', max_length=200, verbose_name='précision sur le style')),
                ('state', models.CharField(choices=[('draft', 'brouillon'), ('published', 'publiée')], default='draft', editable=False, max_length=10, verbose_name='état')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='commencée le')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publiée le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_versions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='translations.translationproject', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['project', 'published_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='latin')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='translations.segment', verbose_name='phrase source')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'phrase traduite',
                'verbose_name_plural': 'phrases traduites',
                'ordering': ['version', 'segment__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='translationversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state', 'draft')), models.Q(('published_at__isnull', False), ('state', 'published')), _connector='OR'), name='translations_version_published_at'),
        ),
        migrations.AddConstraint(
            model_name='translatedsegment',
            constraint=models.UniqueConstraint(fields=('version', 'segment'), name='translations_one_text_per_segment'),
        ),
    ]
