# Generated by Django 6.1.1 on 2026-09-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_translationproject_translationversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationproject',
            name='reference_version',
            field=models.ForeignKey(blank=True, editable=False, help_text='Choisie par le créateur du projet parmi les versions publiées.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='translations.translationversion', verbose_name='version de référence'),
        ),
    ]
