# Generated by Django 6.1.1 on 2026-09-15 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_translationproject_reference_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedsegment',
            name='written_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='écrite par'),
        ),
        migrations.AddField(
            model_name='translationversion',
            name='shows_draft_steps',
            field=models.BooleanField(default=False, editable=False, help_text='Choisi une fois pour toutes à la publication.', verbose_name='étapes du brouillon montrées'),
        ),
        migrations.CreateModel(
            name='VersionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('number', models.PositiveIntegerField(editable=False, verbose_name='numéro')),
                ('message', models.CharField(help_text='Ce qui a changé, par exemple : « phrases 1 à 12 revues ».', max_length=300, verbose_name='message')),
                ('during_draft', models.BooleanField(default=False, editable=False, verbose_name='créée pendant le brouillon')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créée le')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'étape',
                'verbose_name_plural': 'étapes',
                'ordering': ['version', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StepSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='latin')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='translations.segment', verbose_name='phrase source')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='écrite par')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentences', to='translations.versionstep', verbose_name='étape')),
            ],
            options={
                'verbose_name': 'phrase d’une étape',
                'verbose_name_plural': 'phrases d’une étape',
                'ordering': ['step', 'segment__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='versionstep',
            constraint=models.UniqueConstraint(fields=('version', 'number'), name='translations_step_number'),
        ),
        migrations.AddConstraint(
            model_name='stepsentence',
            constraint=models.UniqueConstraint(fields=('step', 'segment'), name='translations_one_text_per_step_segment'),
        ),
    ]
