# Generated by Django 6.1.1 on 2026-09-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_first_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationversion',
            name='copied_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='translations.versionstep', verbose_name='copiée de l’étape'),
        ),
    ]
