# Generated by Django 6.1.1 on 2026-09-15 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_version_copied_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('explanation', models.TextField(help_text='Pourquoi ces changements : tours attestés, fautes corrigées, style visé.', max_length=3000, verbose_name='explication')),
                ('status', models.CharField(choices=[('open', 'ouverte'), ('closed', 'close'), ('withdrawn', 'retirée par son auteur')], default='open', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='proposée le')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='close le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_proposals', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('base_step', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='translations.versionstep', verbose_name='étape de départ')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'proposition de modifications',
                'verbose_name_plural': 'propositions de modifications',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProposedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('base_text', models.TextField(blank=True, editable=False, verbose_name='latin de l’étape de départ')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='latin proposé')),
                ('decision', models.CharField(choices=[('pending', 'en attente'), ('accepted', 'acceptée'), ('refused', 'refusée')], default='pending', editable=False, max_length=10, verbose_name='décision')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='examinée le')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentences', to='translations.changeproposal', verbose_name='proposition')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='translations.segment', verbose_name='phrase source')),
            ],
            options={
                'verbose_name': 'phrase proposée',
                'verbose_name_plural': 'phrases proposées',
                'ordering': ['proposal', 'segment__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='changeproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'open')), models.Q(models.Q(('status', 'open'), _negated=True), ('closed_at__isnull', False)), _connector='OR'), name='translations_proposal_closing'),
        ),
        migrations.AddConstraint(
            model_name='proposedsentence',
            constraint=models.UniqueConstraint(fields=('proposal', 'segment'), name='translations_one_proposed_text_per_segment'),
        ),
    ]
