# Generated by Django 6.1.1 on 2026-09-15 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0008_source_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('explanation', models.TextField(blank=True, help_text='Pourquoi ces changements : fautes corrigées, phrases oubliées, découpage revu.', max_length=3000, verbose_name='explication')),
                ('operations', models.JSONField(default=list, editable=False, verbose_name='changements')),
                ('base_state', models.PositiveIntegerField(editable=False, verbose_name='état du texte de départ')),
                ('status', models.CharField(choices=[('preparing', 'en préparation'), ('open', 'ouverte'), ('adopted', 'adoptée'), ('refused', 'refusée'), ('withdrawn', 'retirée par son auteur')], default='preparing', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='commencée le')),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='envoyée le')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='close le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_proposals', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='examinée par')),
                ('source_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='translations.sourcetext', verbose_name='texte source')),
            ],
            options={
                'verbose_name': 'proposition de modification du texte',
                'verbose_name_plural': 'propositions de modification du texte',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='sourcechange',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='translations.sourceproposal', verbose_name='proposition'),
        ),
        migrations.AddConstraint(
            model_name='sourceproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status__in', ['preparing', 'open'])), models.Q(models.Q(('status__in', ['preparing', 'open']), _negated=True), ('closed_at__isnull', False)), _connector='OR'), name='translations_source_proposal_closing'),
        ),
        migrations.AddConstraint(
            model_name='sourceproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'preparing')), fields=('source_text', 'author'), name='translations_one_source_proposal_in_preparation'),
        ),
    ]
