# Generated by Django 6.1.1 on 2026-09-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0009_source_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('status', models.CharField(choices=[('invited', 'invité'), ('active', 'co-auteur'), ('declined', 'invitation refusée'), ('removed', 'retiré')], default='invited', editable=False, max_length=10, verbose_name='statut')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='invité le')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='réponse le')),
                ('invited_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='invité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_memberships', to=settings.AUTH_USER_MODEL, verbose_name='co-auteur')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'co-auteur d’une version',
                'verbose_name_plural': 'co-auteurs d’une version',
                'ordering': ['version', 'invited_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('version', 'user'), name='translations_one_membership')],
            },
        ),
    ]
