# Generated by Django 6.1.1 on 2026-09-19 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0010_version_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('number', models.PositiveIntegerField(editable=False, verbose_name='numéro')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('body', models.TextField(help_text='Écrivez #3 pour renvoyer au sujet n° 3, @Nom pour prévenir quelqu’un.', max_length=5000, verbose_name='texte')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='étiquettes')),
                ('status', models.CharField(choices=[('open', 'ouvert'), ('closed', 'fermé')], default='open', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ouvert le')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fermé le')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('closed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fermé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='translations.translationproject', verbose_name='projet')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='translations.segment', verbose_name='phrase concernée')),
            ],
            options={
                'verbose_name': 'sujet',
                'verbose_name_plural': 'sujets',
                'ordering': ['project', '-number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='translations_topic_number')],
            },
        ),
    ]
