# Generated by Django 6.1.1 on 2026-09-19 12:14

from django.db import migrations, models


def mark_existing_translated(apps, schema_editor):
    """Sentences written before the statuses existed count as translated."""
    translated = apps.get_model("translations", "TranslatedSegment")
    translated.objects.exclude(text="").update(status="translated")


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0011_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedsegment',
            name='status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('translated', 'traduite'), ('reviewed', 'relue')], default='draft', editable=False, max_length=10, verbose_name='statut'),
        ),
        migrations.RunPython(mark_existing_translated, migrations.RunPython.noop),
    ]
