# Generated by Django 6.1.1 on 2026-09-19 12:23

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0012_sentence_status'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='segment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='translations_segment_trigrams', opclasses=['gin_trgm_ops']),
        ),
    ]
