# Generated by Django 6.1.1 on 2026-09-19 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phraseology', '0021_schema_case_help'),
        ('translations', '0013_segment_trigrams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('source_term', models.CharField(max_length=200, verbose_name='terme source')),
                ('latin_term', models.CharField(max_length=200, verbose_name='latin')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='note')),
                ('status', models.CharField(choices=[('proposed', 'proposé'), ('adopted', 'adopté'), ('rejected', 'écarté')], default='proposed', editable=False, max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='proposé le')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='proposé par')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='décidé par')),
                ('neologism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='glossary_entries', to='phraseology.neologism', verbose_name='néologisme')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary', to='translations.translationproject', verbose_name='projet')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='glossary_entries', to='phraseology.unit', verbose_name='fiche phraséologique')),
            ],
            options={
                'verbose_name': 'terme du glossaire',
                'verbose_name_plural': 'termes du glossaire',
                'ordering': ['project', 'source_term', 'pk'],
            },
        ),
    ]
