# Generated by Django 6.1.1 on 2026-09-19 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0014_glossary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('text', models.TextField(max_length=2000, verbose_name='commentaire')),
                ('is_resolved', models.BooleanField(default=False, editable=False, verbose_name='résolu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='écrit le')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('resolved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='résolu par')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='translations.segment', verbose_name='phrase source')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence_comments', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'commentaire d’une phrase',
                'verbose_name_plural': 'commentaires des phrases',
                'ordering': ['version', 'segment', 'created_at', 'pk'],
            },
        ),
    ]
