# Generated by Django 6.1.1 on 2026-09-19 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0015_sentence_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='vérification')),
                ('fingerprint', models.CharField(max_length=16, verbose_name='empreinte du latin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('ignored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ignorée par')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='translations.segment', verbose_name='phrase source')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_alerts', to='translations.translationversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'alerte ignorée',
                'verbose_name_plural': 'alertes ignorées',
                'constraints': [models.UniqueConstraint(fields=('version', 'segment', 'code', 'fingerprint'), name='translations_one_ignored_alert')],
            },
        ),
    ]
