# Generated by Django 6.1.1 on 2026-09-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0016_ignored_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationversion',
            name='synced_to',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='translations.versionstep', verbose_name='mise à jour jusqu’à l’étape'),
        ),
    ]
