# Generated by Django 6.1.1 on 2026-09-19 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0017_version_synced_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('verdict', models.CharField(choices=[('approve', 'approuve'), ('changes', 'demande des changements'), ('comment', 'commente')], max_length=10, verbose_name='avis')),
                ('text', models.TextField(blank=True, max_length=3000, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='translations.changeproposal', verbose_name='proposition')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='relecteur')),
            ],
            options={
                'verbose_name': 'relecture d’une proposition',
                'verbose_name_plural': 'relectures des propositions',
                'ordering': ['proposal', 'created_at', 'pk'],
            },
        ),
    ]
