# Generated by Django 6.1.1 on 2026-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0018_proposal_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionstep',
            name='label',
            field=models.CharField(blank=True, help_text='Par exemple : « Édition 1 », « Relue par le comité ».', max_length=80, verbose_name='étiquette'),
        ),
    ]
