# Generated by Django 6.1.1 on 2026-09-19 13:24

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0019_step_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='langue source')),
                ('source', models.TextField(max_length=4000, verbose_name='phrase source')),
                ('latin', models.TextField(max_length=4000, verbose_name='latin')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='fichier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='importée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
            ],
            options={
                'verbose_name': 'entrée de la mémoire personnelle',
                'verbose_name_plural': 'entrées de la mémoire personnelle',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['source'], name='translations_memory_trigrams', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
