# Generated by Django 6.1.1 on 2026-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0023_remove_version_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='niveau de titre'),
        ),
        migrations.AddField(
            model_name='sourcetext',
            name='level_names',
            field=models.CharField(blank=True, help_text='Noms des trois niveaux de titre, séparés par des virgules : « Partie, Chapitre, Section ». Laissé vide, ces noms-là sont employés.', max_length=100, verbose_name='noms des divisions'),
        ),
        migrations.AlterField(
            model_name='sourcetext',
            name='text',
            field=models.TextField(help_text='Une phrase par ligne ; une ligne vide entre deux paragraphes ; un titre de division sur sa ligne, précédé de #, ## ou ###.', verbose_name='texte découpé'),
        ),
    ]
