# Generated by Django 6.1.1 on 2026-09-20 19:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0024_segment_level_sourcetext_level_names_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetext',
            name='genres',
            field=models.JSONField(blank=True, default=list, verbose_name='genres'),
        ),
        migrations.AddField(
            model_name='sourcetext',
            name='themes',
            field=models.JSONField(blank=True, default=list, verbose_name='thèmes'),
        ),
        migrations.AddIndex(
            model_name='sourcetext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['genres'], name='translations_source_genres'),
        ),
        migrations.AddIndex(
            model_name='sourcetext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['themes'], name='translations_source_themes'),
        ),
    ]
