# Generated by Django 6.1.1 on 2026-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0025_sourcetext_genres_sourcetext_themes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetext',
            name='license',
            field=models.CharField(choices=[('public-domain', 'domaine public'), ('cc0-1.0', 'CC0 1.0'), ('cc-by-4.0', 'CC BY 4.0'), ('cc-by-3.0', 'CC BY 3.0'), ('cc-by-sa-4.0', 'CC BY-SA 4.0'), ('cc-by-sa-3.0', 'CC BY-SA 3.0')], default='public-domain', max_length=20, verbose_name='licence'),
        ),
    ]
