# Generated by Django 6.1.1 on 2026-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0026_alter_sourcetext_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetext',
            name='author_birth_year',
            field=models.IntegerField(blank=True, help_text='Facultatif. La même année de début de siècle dans les deux cases (1800, ou 1801) situe l’auteur dans ce siècle, sans autre précision.', null=True, verbose_name='année de naissance de l’auteur'),
        ),
    ]
