# Generated by Django 6.1.1 on 2026-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0028_delete_variant_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeproposal',
            name='translations_proposal_closing',
        ),
        migrations.RemoveField(
            model_name='proposalreview',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalreview',
            name='reviewer',
        ),
        migrations.RemoveConstraint(
            model_name='proposedsentence',
            name='translations_one_proposed_text_per_segment',
        ),
        migrations.RemoveConstraint(
            model_name='translationversion',
            name='translations_version_closing',
        ),
        migrations.AddField(
            model_name='translationproject',
            name='open_correction',
            field=models.BooleanField(default=True, help_text='Décochée, seuls les correcteurs, traducteurs et éditeurs nommés ajoutent des variantes aux phrases.', verbose_name='correction ouverte à tous'),
        ),
        migrations.AlterField(
            model_name='sourcetext',
            name='level_names',
            field=models.CharField(blank=True, help_text='Facultatif. Noms des trois niveaux de titre, séparés par des virgules : « Livre, Chapitre, Section ». Laissés vides, les divisions sont citées par leur numéro seul.', max_length=100, verbose_name='noms des divisions'),
        ),
        migrations.RemoveField(
            model_name='changeproposal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='changeproposal',
            name='base_step',
        ),
        migrations.RemoveField(
            model_name='changeproposal',
            name='from_version',
        ),
        migrations.RemoveField(
            model_name='changeproposal',
            name='version',
        ),
        migrations.DeleteModel(
            name='ProposalReview',
        ),
        migrations.RemoveField(
            model_name='proposedsentence',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposedsentence',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='translationversion',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='translationversion',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='translationversion',
            name='synced_to',
        ),
        migrations.RemoveField(
            model_name='translationversion',
            name='variant_status',
        ),
        migrations.DeleteModel(
            name='ChangeProposal',
        ),
        migrations.DeleteModel(
            name='ProposedSentence',
        ),
    ]
