# Generated by Django 6.1.1 on 2026-09-21 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0030_projectmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('text', models.TextField(max_length=4000, verbose_name='latin')),
                ('comment', models.TextField(blank=True, help_text='Pourquoi ce latin : tour attesté, faute corrigée, style visé.', max_length=3000, verbose_name='commentaire')),
                ('status', models.CharField(choices=[('proposal', 'proposition'), ('reference', 'pour référence')], default='proposal', max_length=10, verbose_name='statut')),
                ('decision', models.CharField(blank=True, choices=[('', 'en attente'), ('adopted', 'adoptée'), ('refused', 'refusée')], default='', editable=False, max_length=10, verbose_name='décision')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajoutée le')),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='décidée le')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='segment_variants', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='décidée par')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='translations.segment', verbose_name='phrase source')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='translations.segmentvariant', verbose_name='variante corrigée')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='translations.translationversion', verbose_name='traduction')),
            ],
            options={
                'verbose_name': 'variante d’une phrase',
                'verbose_name_plural': 'variantes des phrases',
                'ordering': ['segment__position', 'created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decision', '')), models.Q(models.Q(('decision', ''), _negated=True), ('decided_at__isnull', False)), _connector='OR'), name='translations_variant_decision')],
            },
        ),
    ]
