# Generated by Django 6.1.1 on 2026-09-13 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
        ('translations', '0003_translationproject_reference_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=30, unique=True, verbose_name='abréviation')),
                ('title', models.CharField(max_length=300, verbose_name='titre')),
                ('kind', models.CharField(choices=[('grammar', 'grammaire'), ('dictionary', 'dictionnaire')], max_length=20, verbose_name='type')),
                ('rights', models.CharField(choices=[('free', 'libre de droits'), ('restricted', 'sous droits : cité seulement')], default='restricted', max_length=20, verbose_name='droits')),
            ],
            options={
                'verbose_name': 'ouvrage de référence',
                'verbose_name_plural': 'ouvrages de référence',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('latin_excerpt', models.CharField(help_text='Les mots de votre phrase latine que vous justifiez, tels quels.', max_length=500, verbose_name='passage latin justifié')),
                ('latin_start', models.PositiveIntegerField(default=0, verbose_name='position du passage')),
                ('source_excerpt', models.CharField(blank=True, help_text='Facultatif : les mots du texte source que ce passage traduit.', max_length=500, verbose_name='passage du texte source')),
                ('strength', models.PositiveSmallIntegerField(choices=[(1, 'attesté tel quel en prose classique'), (2, 'attesté avec variante'), (3, 'attesté seulement en poésie ou à basse époque'), (4, 'par analogie'), (5, 'introuvable dans le corpus')], help_text='De la plus forte (1) à la plus faible (5).', verbose_name='force de preuve')),
                ('comment', models.TextField(blank=True, help_text='Obligatoire pour une justification par analogie.', max_length=3000, verbose_name='commentaire')),
                ('corpus_version', models.CharField(blank=True, help_text='Enregistrée quand le passage est introuvable dans le corpus (règle 7).', max_length=200, verbose_name='version du corpus interrogé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créée le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justifications', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('translated_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justifications', to='translations.translatedsegment', verbose_name='phrase traduite')),
            ],
            options={
                'verbose_name': 'justification',
                'verbose_name_plural': 'justifications',
                'ordering': ['translated_segment', 'latin_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('kind', models.CharField(choices=[('corpus', 'attestation du corpus'), ('grammar', 'règle de grammaire'), ('dictionary', 'article de dictionnaire')], max_length=20, verbose_name='type')),
                ('locator', models.CharField(blank=True, help_text='Paragraphe, page ou entrée : « § 426 », « s. v. consilium ».', max_length=100, verbose_name='localisation')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='retirée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajoutée le')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('tokens', models.ManyToManyField(blank=True, related_name='+', to='corpus.token', verbose_name='mots cités')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='justifications.bibliographicwork', verbose_name='ouvrage')),
                ('justification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='justifications.justification', verbose_name='justification')),
            ],
            options={
                'verbose_name': 'preuve',
                'verbose_name_plural': 'preuves',
                'ordering': ['justification', 'created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='justification',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1), ('strength__lte', 5)), name='justifications_strength_scale'),
        ),
        migrations.AddConstraint(
            model_name='justification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('strength', 4), _negated=True), models.Q(('comment', ''), _negated=True), _connector='OR'), name='justifications_analogy_has_comment', violation_error_message='Une justification par analogie exige un commentaire.'),
        ),
        migrations.AddConstraint(
            model_name='justification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('strength', 5), _negated=True), models.Q(('corpus_version', ''), _negated=True), _connector='OR'), name='justifications_not_found_has_corpus_version'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'corpus'), ('passage__isnull', False), ('work__isnull', True)), models.Q(models.Q(('kind', 'corpus'), _negated=True), ('passage__isnull', True), ('work__isnull', False), models.Q(('locator', ''), _negated=True)), _connector='OR'), name='justifications_evidence_kind'),
        ),
    ]
