# Generated by Django 6.1.1 on 2026-09-13 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
        ('justifications', '0002_bibliographic_works'),
        ('translations', '0003_translationproject_reference_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='justification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='justifications.justification', verbose_name='justification'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='masqué')),
                ('latin_excerpt', models.CharField(help_text='Les mots contestés, tels qu’ils sont écrits.', max_length=500, verbose_name='passage contesté')),
                ('latin_start', models.PositiveIntegerField(default=0, verbose_name='position du passage')),
                ('argument', models.TextField(help_text='Pourquoi ce choix vous paraît fautif, et ce que vous proposez à la place.', max_length=5000, verbose_name='argument')),
                ('status', models.CharField(choices=[('open', 'ouverte'), ('upheld', 'retenue'), ('dismissed', 'écartée'), ('withdrawn', 'retirée par son auteur')], default='open', editable=False, max_length=10, verbose_name='statut')),
                ('resolution', models.TextField(blank=True, editable=False, max_length=3000, verbose_name='décision motivée')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='close le')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ouverte le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('closed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='close par')),
                ('justification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='justifications.justification', verbose_name='justification contestée')),
                ('translated_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='translations.translatedsegment', verbose_name='phrase traduite')),
            ],
            options={
                'verbose_name': 'contestation',
                'verbose_name_plural': 'contestations',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='justifications.challenge', verbose_name='contestation'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('challenge__isnull', True), ('justification__isnull', False)), models.Q(('challenge__isnull', False), ('justification__isnull', True)), _connector='OR'), name='justifications_evidence_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('status', 'open')), models.Q(models.Q(('status', 'open'), _negated=True), ('closed_at__isnull', False), ('closed_by__isnull', False)), _connector='OR'), name='justifications_challenge_closing'),
        ),
    ]
