# Generated by Django 6.1.1 on 2026-09-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_analysislayer_tokenanalysis_and_more'),
        ('justifications', '0003_alter_evidence_justification_challenge_and_more'),
        ('phraseology', '0003_neologism_neologismequivalent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evidence',
            name='justifications_evidence_one_parent',
        ),
        migrations.AddField(
            model_name='evidence',
            name='neologism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='phraseology.neologism', verbose_name='néologisme'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('challenge__isnull', True), ('justification__isnull', False), ('neologism__isnull', True)), models.Q(('challenge__isnull', False), ('justification__isnull', True), ('neologism__isnull', True)), models.Q(('challenge__isnull', True), ('justification__isnull', True), ('neologism__isnull', False)), _connector='OR'), name='justifications_evidence_one_parent'),
        ),
    ]
