# Generated by Django 6.1.1 on 2026-09-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0004_remove_evidence_justifications_evidence_one_parent_and_more'),
        ('phraseology', '0005_unitform'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='attestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='phraseology.attestation', verbose_name='attestation d’une fiche'),
        ),
        migrations.AddField(
            model_name='justification',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='justifications', to='phraseology.unit', verbose_name='fiches phraséologiques citées'),
        ),
    ]
