# Generated by Django 6.1.1 on 2026-09-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0005_evidence_attestation_justification_units'),
        ('translations', '0004_translatedsegment_written_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='step',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='translations.versionstep', verbose_name='étape contestée'),
        ),
    ]
