# Generated by Django 6.1.1 on 2026-09-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0007_challenge_steps'),
        ('translations', '0005_first_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='step',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justifications', to='translations.versionstep', verbose_name='étape de parution'),
        ),
    ]
