# Generated by Django 6.1.1 on 2026-09-14 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0005_analysis_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('yellow', 'jaune'), ('green', 'vert'), ('blue', 'bleu'), ('pink', 'rose')], default='yellow', max_length=10, verbose_name='couleur')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('tokens', models.ManyToManyField(related_name='+', to='corpus.token', verbose_name='mots')),
            ],
            options={
                'verbose_name': 'surlignage',
                'verbose_name_plural': 'surlignages',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PassageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créée le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_lists', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'liste de passages',
                'verbose_name_plural': 'listes de passages',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PassageListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='ajouté le')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('passage_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='notebook.passagelist', verbose_name='liste')),
            ],
            options={
                'verbose_name': 'passage d’une liste',
                'verbose_name_plural': 'passages des listes',
                'ordering': ['added_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='passagelist',
            name='passages',
            field=models.ManyToManyField(related_name='+', through='notebook.PassageListEntry', to='corpus.passage', verbose_name='passages'),
        ),
        migrations.CreateModel(
            name='PrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créée le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='corpus.passage', verbose_name='passage')),
                ('tokens', models.ManyToManyField(related_name='+', to='corpus.token', verbose_name='mots')),
            ],
            options={
                'verbose_name': 'note privée',
                'verbose_name_plural': 'notes privées',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='passagelistentry',
            constraint=models.UniqueConstraint(fields=('passage_list', 'passage'), name='notebook_one_entry_per_passage'),
        ),
        migrations.AddConstraint(
            model_name='passagelist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='notebook_one_list_name'),
        ),
    ]
